controller_list:
  - name: fake_right_arm_controller
    joints:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
  - name: fake_left_arm_controller
    joints:
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint
      - arm_left_4_joint
      - arm_left_5_joint
      - arm_left_6_joint
      - arm_left_7_joint
  - name: fake_right_arm_torso_controller
    joints:
      - torso_1_joint
      - torso_2_joint
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
  - name: fake_left_arm_torso_controller
    joints:
      - torso_1_joint
      - torso_2_joint
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint
      - arm_left_4_joint
      - arm_left_5_joint
      - arm_left_6_joint
      - arm_left_7_joint
  - name: fake_both_arms_controller
    joints:
      - torso_1_joint
      - torso_2_joint
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint
      - arm_left_4_joint
      - arm_left_5_joint
      - arm_left_6_joint
      - arm_left_7_joint
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
  - name: fake_right_hand_controller
    joints:
      - hand_right_index_1_joint
      - hand_right_index_2_joint
      - hand_right_index_3_joint
      - hand_right_middle_1_joint
      - hand_right_middle_2_joint
      - hand_right_middle_3_joint
      - hand_right_thumb_joint
  - name: fake_left_hand_controller
    joints:
      - hand_left_index_1_joint
      - hand_left_index_2_joint
      - hand_left_index_3_joint
      - hand_left_middle_1_joint
      - hand_left_middle_2_joint
      - hand_left_middle_3_joint
      - hand_left_thumb_joint
  - name: fake_head_controller
    joints:
      - head_1_joint
      - head_2_joint
  - name: fake_both_arms_and_head_controller
    joints:
      - torso_1_joint
      - torso_2_joint
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint
      - arm_left_4_joint
      - arm_left_5_joint
      - arm_left_6_joint
      - arm_left_7_joint
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
      - head_1_joint
      - head_2_joint
  - name: fake_right_hand_grasping_controller
    joints:
      - hand_right_index_1_joint
      - hand_right_index_2_joint
      - hand_right_index_3_joint
      - hand_right_index_joint
      - hand_right_middle_1_joint
      - hand_right_middle_2_joint
      - hand_right_middle_3_joint
      - hand_right_middle_joint
      - hand_right_thumb_joint
  - name: fake_right_arm_torso_grasping_controller
    joints:
      - torso_1_joint
      - torso_2_joint
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
  - name: fake_left_arm_torso_grasping_controller
    joints:
      - torso_1_joint
      - torso_2_joint
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint
      - arm_left_4_joint
      - arm_left_5_joint
      - arm_left_6_joint
      - arm_left_7_joint
  - name: fake_left_hand_grasping_controller
    joints:
      - hand_left_index_1_joint
      - hand_left_index_2_joint
      - hand_left_index_3_joint
      - hand_left_index_joint
      - hand_left_middle_1_joint
      - hand_left_middle_2_joint
      - hand_left_middle_3_joint
      - hand_left_middle_joint
      - hand_left_thumb_joint